### ISSUE TITLE
Bioconda recipe feedback needed

### ISSUE THREAD

**Issue by rpetit3** [molloy-lab/TREE-QMC#4]
Hello!

We currently have 2 recipes for TREE-QMC on Bioconda: `treeqmc` and `tree-qmc`

https://bioconda.github.io/recipes/treeqmc/README.html
https://bioconda.github.io/recipes/tree-qmc/README.html

Is there a need for both, or can we just use one since they are identical? If OK, with one, which would you prefer?

Thank you for your help!
Robert

**Comment by ekmolloy** [comment]
Hi Robert,

My student is updating the bioconda receipe for https://github.com/bioconda/bioconda-recipes/tree/master/recipes/tree-qmc

so I think we want to use this link https://bioconda.github.io/recipes/tree-qmc/README.html

Thank you!
Erin

**Comment by rpetit3** [comment]
Thank you! I'll get the `treeqmc` to stop receiving updates
